asm mul, sub added
Rai-Fox/first-term pull request #2
Opened 2020-07-04 20:40 UTC by Rai-Fox

2020-07-06 23:43 UTC, kt-cpp commented on asm/mul.asm
> +;    result is written to rdi
В контракте баг

2020-07-06 23:43 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rdi, [r9]
Давай без `lea` тут ...

2020-07-06 23:43 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 6 * SIZE
Выдели доп память в `mul_long_long`, еще заметишь что тебе хватит `(SIZE + 1) * sizeof(qword)`

2020-07-06 23:45 UTC, kt-cpp commented on asm/mul.asm
> +                ; set zero to tmp, ans, r11
`r11`?

2020-07-06 23:46 UTC, kt-cpp commented on asm/sub.asm
> +;    rsi -- address of summand #2 (long number)
not a summand

2020-07-06 23:47 UTC, kt-cpp commented on asm/mul.asm
> +                inc             r12
Может `r12` тоже двигать на 8?

2020-07-06 23:48 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rdi, [r8]
Что-то ты часто используешь `lea` вместо `mov`

2020-07-06 23:49 UTC, kt-cpp requested changes
В целом мелкие недочеты, но давай уменьшим память под грязные вычисления (копирование одного из множителей и умножение на разряд другого) с 256 * 8 до 128(129) * 8

2020-10-14 22:54 UTC, Rai-Fox commented on asm/mul.asm
> +;    result is written to rdi
fixed

2020-10-14 22:55 UTC, Rai-Fox commented on asm/mul.asm
> +                lea             rdi, [r9]
fixed

2020-10-14 22:55 UTC, Rai-Fox commented on asm/mul.asm
> +                sub             rsp, 6 * SIZE
fixed

2020-10-14 22:55 UTC, Rai-Fox commented on asm/mul.asm
> +                ; set zero to tmp, ans, r11
fixed

2020-10-14 22:57 UTC, Rai-Fox commented on asm/mul.asm
> +                inc             r12
Я также использую значение r12 в qword'ах, сдвигать на 8 не получится

2020-10-14 22:57 UTC, Rai-Fox commented on asm/mul.asm
> +                lea             rdi, [r8]
fixed

2020-10-14 23:34 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rdi, [r9]
Не fixed

2020-10-14 23:36 UTC, Rai-Fox commented on asm/mul.asm
> +                lea             rdi, [r9]
ой, думал все исправил

2020-10-14 23:46 UTC, kt-cpp commented on asm/mul.asm
> +;    r12 -- offset
В контракте не написано , что исопльзуется регистр `r15`. Мне пришлось долго понимать, почему твое умножение работает :(

2020-10-14 23:50 UTC, kt-cpp commented
Подправь, пожалуйста контракты, назови может быть функцию `add_long_long` по-другому (чтобы внести в нее информацию о том, что она по оффсету и добавляет carry)

А так все норм

2020-10-15 00:05 UTC, Rai-Fox commented on asm/mul.asm
> +;    r12 -- offset
fixed

2020-10-15 00:17 UTC, merged

2020-10-15 00:17 UTC, kt-cpp commented
Ok