Bigint
Rai-Fox/first-term pull request #3
Opened 2020-10-04 16:52 UTC by Rai-Fox

big_integer added

2020-10-06 11:23 UTC, kt-cpp requested changes

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::big_integer() : digits_(), sign_(_POSITIVE) {}
Учитывая устройство класса, можно было написать `= default` еще в хедере и не писать реализацию.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::big_integer(big_integer const& a) {
Действие этого конструктора совпадает с автоматически сгенерированным, поэтому целесообразно написать в хедере `= default`.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
Форматирование.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +	if (a != 0)
Либо во всех однострочных ифах делаем блок (`{}`), либо во всех не делаем.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
Правда, что этот конструктор примет число вроде `123-+-+567`? Кажется, так не должно быть.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer& big_integer::operator=(big_integer const& other) {
Этот конструктор тоже тожно было сделать дефолтным.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
Ну оочень много совершенно не нужных копирований. Этот метод можно (и просто) написать, используя лишь `result` и входные данные.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
Кроме того, лично я бы советовал делать вручную `operator+=`, а через него выражать `operator+`. Дело в том, что первый можно написать вообще без конструирования нового `big_int`. В худшем случае, понадобится расширить вектор. А во втором операторе по-любому придется создавать новый `big_int`, поэтому его можно легко и без особых потерь написать через `+=`, приняв первый аргумент, например, по значению.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
Эти комментарии относятся так же и к остальным операторам.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +}
Вот в этом операторе уж точно никакого копирования быть не должно.

2020-10-06 11:23 UTC, kt-cpp commented on bigint/big_integer.cpp
> +
Зачем здесь копировать `b`? Ты не не изменяешь его значения.

2020-10-06 18:50 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +big_integer::big_integer() : digits_(), sign_(_POSITIVE) {}
fixed

2020-10-06 18:50 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +big_integer::big_integer(big_integer const& a) {
fixed

2020-10-06 18:51 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +    }
Это вообще какой-то старый код, у меня такого нет

2020-10-06 18:51 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +	if (a != 0)
Это вообще какой-то старый код, у меня такого нет (2)

2020-10-06 18:51 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +}
fixed

2020-10-06 18:51 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +big_integer& big_integer::operator=(big_integer const& other) {
fixed

2020-10-06 18:51 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +}
fixed

2020-10-06 18:51 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +}
fixed

2020-10-06 18:52 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +
fixed

2020-10-07 08:24 UTC, dzhiblavi requested changes
В целом намного лучше. Пара копирований осталось: все-таки надо сделать `+=`, `-=` без копий.

2020-10-07 08:24 UTC, dzhiblavi commented on bigint/big_integer.cpp
> +		return *this -= (-b);
Здесь происходит лишнее копирование.

2020-10-07 08:24 UTC, dzhiblavi commented on bigint/big_integer.cpp
>  		big_integer result;
Здесь тоже копирование

2020-10-07 08:24 UTC, dzhiblavi commented on bigint/big_integer.cpp
> +		return *this += (-b);
И здесь копирование.

2020-10-07 08:27 UTC, kt-cpp requested changes
А я случайно написал ревью не с того акка)

2020-10-07 09:33 UTC, Rai-Fox commented on bigint/big_integer.cpp
>  		big_integer result;
Кажется, тут его нет, просто я забыл result убрать

2020-10-07 11:30 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +		return *this -= (-b);
fixed

2020-10-07 11:30 UTC, Rai-Fox commented on bigint/big_integer.cpp
> +		return *this += (-b);
fixed

2020-10-07 11:50 UTC, kt-cpp approved these changes

2020-10-07 11:50 UTC, merged